apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: meu-deploy
spec:
  replicas: 15
  selector:
    matchLabels:
      app: meu-conversao-distancia
  template:
    metadata:
      labels:
        app: meu-conversao-distancia
    spec:
      containers:
      - name: meu-container
        image: tiagotas/conversao-distancia:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: meu-service
spec:
  selector:
    app: meu-conversao-distancia
  ports:
    - protocol: TCP
      port: 5000 # porta do serviço
      targetPort: 5000 # porta do container
  type: LoadBalancer # ou NodePort, ClusterIP, etc.