apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
  name: meu-replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: meu-conversao-distancia
  template:
    metadata:
      labels:
        app: meu-conversao-distancia
    spec:
      containers:
      - name: meu-container
        image: tiagotas/conversao-distancia:latest
        ports:
        - containerPort: 5000