# Kubernetes ReplicaSet para o projeto de conversão de distância
# 1) kubectl api-resource
# 2) kubectl apply -f replicaset.yaml
# 3) kubectl get pods -o wide
# 4) kubectl get rs
# 5) kubectl describe replicaset meu-replicaset
# 6) alterar o número de réplicas para 15 e rode: kubectl apply -f replicaset.yaml && watch 'kubectl get pod'
# 7) kubectl port-forward pod/meu-replicaset-zjwkn 5001:5000
# 8) kubectl delete replicaset meu-replicaset
apiVersion: apps/v1
kind: ReplicaSet 
metadata: 
  name: meu-replicaset
spec:
  replicas: 15
  selector:
    matchLabels:
      app: meu-conversao-distancia
  template:
    metadata:
      labels:
        app: meu-conversao-distancia
    spec:
      containers:
      - name: meu-container
        image: tiagotas/conversao-distancia:latest
        ports:
        - containerPort: 5000