# 1) kubectl api-resource
# 2) kubectl create -f pod.yaml
# 3) kubectl get pods
# 4) kubectl get pods -o wide
# 5) kubectl describe pod meu-pod
# 6) kubectl port-forward meu-pod 5001:5000 (5001 é a porta do pc hospedeiro e 5000 é a porta do container)
# 7) kubectl delete pod meu-pod

apiVersion: v1 # comando: kubectl create -f pod.yaml  / comando: kubectl api-resource
kind: Pod # comando: kubectl get pods / kubectl get pods -o wide
metadata: # comando: kubectl describe pod my-pod
  name: meu-pod
spec:
  containers:
    - name: meu-container
      image: tiagotas/conversao-distancia:latest
      ports:
        - containerPort: 5000
      